In [1]:
import numpy as np
import pandas as pd

In [2]:
books=pd.read_csv('final_200_books_clean.csv')
users=pd.read_csv('indian_users_800.csv')
ratings=pd.read_csv('user_book_ratings_full_updated_plus300.csv')

In [3]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Availability
0,9780131103627,The C Programming Language,Brian W. Kernighan & Dennis M. Ritchie,1988,Prentice Hall,https://covers.openlibrary.org/b/isbn/97801311...,https://covers.openlibrary.org/b/isbn/97801311...,https://covers.openlibrary.org/b/isbn/97801311...,https://www.amazon.in/dp/0131103628
1,9780134997193,Computer Organization and Architecture,William Stallings,2019,Pearson Education,https://covers.openlibrary.org/b/isbn/97801349...,https://covers.openlibrary.org/b/isbn/97801349...,https://covers.openlibrary.org/b/isbn/97801349...,https://williamstallings.com/ComputerOrganizat...
2,9780195154559,Computer Architecture,Behrooz Parhami,2005,Oxford University Press,https://covers.openlibrary.org/b/isbn/97801951...,https://covers.openlibrary.org/b/isbn/97801951...,https://covers.openlibrary.org/b/isbn/97801951...,https://www.amazon.in/dp/019515455X
3,9780128119051,Computer Architecture: A Quantitative Approach,Patterson & Hennessy,2017,Elsevier,https://covers.openlibrary.org/b/isbn/97801281...,https://covers.openlibrary.org/b/isbn/97801281...,https://covers.openlibrary.org/b/isbn/97801281...,https://www.elsevier.com/books/computer-archit...
4,9788175152571,Fundamentals of Data Structures,Horowitz & Sahani,2008,Galgotia Publications,https://covers.openlibrary.org/b/isbn/97881751...,https://covers.openlibrary.org/b/isbn/97881751...,https://covers.openlibrary.org/b/isbn/97881751...,https://www.amazon.in/dp/8175152575

In [4]:
users.head()

  User-ID        Location  Age
0    U001   Nagpur, India   26
1    U002   Mumbai, India   19
2    U003   Jaipur, India   21
3    U004   Kanpur, India   27
4    U005  Dhanbad, India   33

In [5]:
ratings.head()

  User-ID           ISBN  Book-Rating
0    U001  9781259002380            0
1    U002  9788131791862            2
2    U003  9780073523323           10
3    U004  9780262033848            8
4    U005  9781420089654            8

In [6]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(199, 9)
(4706, 3)
(800, 3)

In [7]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            0
Year-Of-Publication    0
Publisher              0
Image-URL-S            0
Image-URL-M            0
Image-URL-L            0
Availability           0
dtype: int64

In [8]:
users.isnull().sum()

User-ID     0
Location    0
Age         0
dtype: int64

In [9]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [10]:
books.duplicated().sum()

np.int64(3)

In [11]:
books.duplicated().sum()

np.int64(3)

## Popularity based Recommendation System

In [12]:
ratings

     User-ID           ISBN  Book-Rating
0       U001  9781259002380            0
1       U002  9788131791862            2
2       U003  9780073523323           10
3       U004  9780262033848            8
4       U005  9781420089654            8
...      ...            ...          ...
4701    U430  9788187572680            6
4702    U236   978000000110            6
4703    U234  9780071770569            4
4704    U756  9780140449136            4
4705    U385  9788121908716            2

[4706 rows x 3 columns]

In [13]:
ratings_with_name=ratings.merge(books,on='ISBN')

In [14]:
ratings_with_name.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Availability
0,U001,9781259002380,0,Electronic Principles,"Albert Paul Malvino, David Bates",2015,McGraw-Hill Education,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://www.amazon.in/dp/1259002380
1,U001,9781259002380,0,Basic Electronics,"Bernard Grob, Mitchel E. Schultz",2014,McGraw-Hill Education,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://www.amazon.in/dp/1259002380
2,U001,9781259002380,0,Switching Theory and Logic Design,A. Anand Kumar,2016,Prentice Hall,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://www.amazon.in/dp/1259002380
3,U001,9781259002380,0,Electrical Machinery,P.S. Bimbhra,2014,Khanna Publishers,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://www.amazon.in/dp/1259002380
4,U002,9788131791862,2,Power Electronics,P.S. Bimbhra,2012,Khanna Publishers,https://covers.openlibrary.org/b/isbn/97881317...,https://covers.openlibrary.org/b/isbn/97881317...,https://covers.openlibrary.org/b/isbn/97881317...,https://www.amazon.in/dp/8131791863

In [15]:
num_rating_df=ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)
num_rating_df

                                            Book-Title  num_ratings
0                                                 1984           33
1                     Advanced Engineering Mathematics           25
2                         Advanced Structural Analysis           35
3                                  Aircraft Structures           28
4    An Introduction to Data Structures with Applic...           28
..                                                 ...          ...
182  Transport Processes and Separation Process Pri...           52
183                                   Vehicle Dynamics           28
184                             Wastewater Engineering           23
185                           Water Supply Engineering           22
186          Zen and the Art of Motorcycle Maintenance           25

[187 rows x 2 columns]

In [16]:
avg_rating_df=ratings_with_name.groupby('Book-Title')['Book-Rating'].mean().reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_ratings'},inplace=True)
avg_rating_df

                                            Book-Title  avg_ratings
0                                                 1984     5.545455
1                     Advanced Engineering Mathematics     4.920000
2                         Advanced Structural Analysis     4.885714
3                                  Aircraft Structures     5.285714
4    An Introduction to Data Structures with Applic...     5.035714
..                                                 ...          ...
182  Transport Processes and Separation Process Pri...     5.615385
183                                   Vehicle Dynamics     6.464286
184                             Wastewater Engineering     5.217391
185                           Water Supply Engineering     5.545455
186          Zen and the Art of Motorcycle Maintenance     5.120000

[187 rows x 2 columns]

In [17]:
popular_df=num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

,Book-Title,num_ratings,avg_ratings
0,1984,33,5.545455
1,Advanced Engineering Mathematics,25,4.920000
2,Advanced Structural Analysis,35,4.885714
3,Aircraft Structures,28,5.285714
4,An Introduction to Data Structures with Applic...,28,5.035714
...,...,...,...
182,Transport Processes and Separation Process Pri...,52,5.615385
183,Vehicle Dynamics,28,6.464286
184,Wastewater Engineering,23,5.217391
185,Water Supply Engineering,22,5.545455
186,Zen and the Art of Motorcycle Maintenance,25,5.120000

In [18]:
popular_df[popular_df['num_ratings']>=20].sort_values('avg_ratings',ascending=False).head(50)

,Book-Title,num_ratings,avg_ratings
123,Mechanical Engineering Handbook Vol. 8,21,6.809524
136,Operating System Concepts,27,6.666667
62,Harry Potter and the Sorcerer's Stone,23,6.565217
126,Mechanics of Materials,24,6.541667
183,Vehicle Dynamics,28,6.464286
84,Information Technology Guide Vol. 8,24,6.458333
155,Software Defined Networks,22,6.454545
108,Mechanical Engineering Handbook Vol. 12,33,6.393939
172,The Lord of the Rings,21,6.380952
14,Brave New World,31,6.290323
143,Principles of Mass Transfer and Separation Pro...,31,6.290323
131,"Modern Electric, Hybrid Electric, and Fuel Cel...",28,6.250000
109,Mechanical Engineering Handbook Vol. 13,27,6.222222
97,Irrigation and Water Power Engineering,26,6.153846
15,Bridge Engineering,26,6.153846
66,Information Technology Guide Vol. 1,20,6.150000
159,Surveying Vol. 1,58,6.137931
72,Information Technology Guide Vol. 15,29,6.137931
110,Mechanical Engineering Handbook Vol. 14,25,6.120000
94,Introduction to Operations Research,52,6.115385
32,Digital Design,27,6.111111
21,Communication Systems,27,6.074074
85,Information Technology Guide Vol. 9,22,6.045455
61,Harry Potter and the Philosopher's Stone,25,6.040000
174,The Road,25,6.040000
154,Signals and Systems,22,6.000000
63,Highway Engineering,22,6.000000
152,Schaum's Outline of Discrete Mathematics,26,6.000000
157,Strength of Materials,23,5.956522
41,Electrical Engineering Fundamentals,22,5.954545
181,Tool Engineering and Design,30,5.933333
161,Surveying Vol. 3,23,5.913043
124,Mechanical Engineering Handbook Vol. 9,27,5.888889
168,The Design and Implementation of the 4.4 BSD U...,25,5.880000
83,Information Technology Guide Vol. 7,24,5.875000
100,Machine Learning: An AI Approach,24,5.875000
99,Lightweight Electric/Hybrid Vehicle Design,23,5.869565
57,Fundamental Numerical Methods for Electrical E...,26,5.807692
91,Introduction to Environmental Engineering,31,5.806452
73,Information Technology Guide Vol. 16,20,5.800000
141,Principles of Electronics,23,5.782609
114,Mechanical Engineering Handbook Vol. 18,23,5.782609
22,Computer Architecture,22,5.772727
68,Information Technology Guide Vol. 11,30,5.766667
35,Digital Logic and Computer Design,25,5.760000
40,Electric and Hybrid Vehicles: Design Fundament...,25,5.760000
28,Control Systems Engineering,49,5.755102
92,Introduction to Flight,29,5.724138
163,The Alchemist,25,5.720000
44,Electronic Communication Systems,21,5.714286

In [19]:
popular_df

,Book-Title,num_ratings,avg_ratings
0,1984,33,5.545455
1,Advanced Engineering Mathematics,25,4.920000
2,Advanced Structural Analysis,35,4.885714
3,Aircraft Structures,28,5.285714
4,An Introduction to Data Structures with Applic...,28,5.035714
...,...,...,...
182,Transport Processes and Separation Process Pri...,52,5.615385
183,Vehicle Dynamics,28,6.464286
184,Wastewater Engineering,23,5.217391
185,Water Supply Engineering,22,5.545455
186,Zen and the Art of Motorcycle Maintenance,25,5.120000

In [20]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Availability
0,9780131103627,The C Programming Language,Brian W. Kernighan & Dennis M. Ritchie,1988,Prentice Hall,https://covers.openlibrary.org/b/isbn/97801311...,https://covers.openlibrary.org/b/isbn/97801311...,https://covers.openlibrary.org/b/isbn/97801311...,https://www.amazon.in/dp/0131103628
1,9780134997193,Computer Organization and Architecture,William Stallings,2019,Pearson Education,https://covers.openlibrary.org/b/isbn/97801349...,https://covers.openlibrary.org/b/isbn/97801349...,https://covers.openlibrary.org/b/isbn/97801349...,https://williamstallings.com/ComputerOrganizat...
2,9780195154559,Computer Architecture,Behrooz Parhami,2005,Oxford University Press,https://covers.openlibrary.org/b/isbn/97801951...,https://covers.openlibrary.org/b/isbn/97801951...,https://covers.openlibrary.org/b/isbn/97801951...,https://www.amazon.in/dp/019515455X
3,9780128119051,Computer Architecture: A Quantitative Approach,Patterson & Hennessy,2017,Elsevier,https://covers.openlibrary.org/b/isbn/97801281...,https://covers.openlibrary.org/b/isbn/97801281...,https://covers.openlibrary.org/b/isbn/97801281...,https://www.elsevier.com/books/computer-archit...
4,9788175152571,Fundamentals of Data Structures,Horowitz & Sahani,2008,Galgotia Publications,https://covers.openlibrary.org/b/isbn/97881751...,https://covers.openlibrary.org/b/isbn/97881751...,https://covers.openlibrary.org/b/isbn/97881751...,https://www.amazon.in/dp/8175152575

In [21]:
popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')

,Book-Title,num_ratings,avg_ratings,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Availability
0,1984,33,5.545455,9780451524935,George Orwell,1949,Signet Classics,https://covers.openlibrary.org/b/isbn/97804515...,https://covers.openlibrary.org/b/isbn/97804515...,https://covers.openlibrary.org/b/isbn/97804515...,https://www.amazon.in/dp/0451524934
1,Advanced Engineering Mathematics,25,4.920000,9780470458365,Erwin Kreyszig,2011,Wiley,https://covers.openlibrary.org/b/isbn/97804704...,https://covers.openlibrary.org/b/isbn/97804704...,https://covers.openlibrary.org/b/isbn/97804704...,https://www.amazon.com/Advanced-Engineering-Ma...
2,Advanced Structural Analysis,35,4.885714,9780070659155,Devdas Menon,2014,Narosa Publishing House,https://covers.openlibrary.org/b/isbn/97800706...,https://covers.openlibrary.org/b/isbn/97800706...,https://covers.openlibrary.org/b/isbn/97800706...,https://www.amazon.in/dp/0070659153
3,Aircraft Structures,28,5.285714,9788131518155,David J. Peery,2013,McGraw-Hill Education,https://covers.openlibrary.org/b/isbn/97881315...,https://covers.openlibrary.org/b/isbn/97881315...,https://covers.openlibrary.org/b/isbn/97881315...,https://www.amazon.in/dp/8131518155
4,An Introduction to Data Structures with Applic...,28,5.035714,9780074624715,Tremblay & Sorenson,1984,McGraw-Hill,https://covers.openlibrary.org/b/isbn/97800746...,https://covers.openlibrary.org/b/isbn/97800746...,https://covers.openlibrary.org/b/isbn/97800746...,https://www.amazon.in/dp/0074624717
...,...,...,...,...,...,...,...,...,...,...,...
193,Transport Processes and Separation Process Pri...,52,5.615385,9781259062766,Christie J. Geankoplis,2013,Prentice Hall,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://www.amazon.in/dp/1259062763
195,Vehicle Dynamics,28,6.464286,9788131518780,Reza N. Jazar,2014,Springer,https://covers.openlibrary.org/b/isbn/97881315...,https://covers.openlibrary.org/b/isbn/97881315...,https://covers.openlibrary.org/b/isbn/97881315...,https://www.amazon.in/dp/8131518783
196,Wastewater Engineering,23,5.217391,9788121916667,Metcalf & Eddy,2014,McGraw-Hill Education,https://covers.openlibrary.org/b/isbn/97881219...,https://covers.openlibrary.org/b/isbn/97881219...,https://covers.openlibrary.org/b/isbn/97881219...,https://www.amazon.in/dp/8121916666
197,Water Supply Engineering,22,5.545455,9788121916650,"B.C. Punmia, Ashok Kumar Jain, Arun Kumar Jain",2008,Laxmi Publications,https://covers.openlibrary.org/b/isbn/97881219...,https://covers.openlibrary.org/b/isbn/97881219...,https://covers.openlibrary.org/b/isbn/97881219...,https://www.amazon.in/dp/8121916658
198,Zen and the Art of Motorcycle Maintenance,25,5.120000,9780385472579,Robert M. Pirsig,1974,William Morrow & Company,https://covers.openlibrary.org/b/isbn/97803854...,https://covers.openlibrary.org/b/isbn/97803854...,https://covers.openlibrary.org/b/isbn/97803854...,https://www.amazon.in/dp/0385472579

In [22]:
merged_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','num_ratings','avg_ratings','Availability']]
merged_df['Image-URL-M'].iloc[20]

'https://covers.openlibrary.org/b/isbn/9780132350884-M.jpg'

## Collaborative based filtering

In [23]:
x=ratings_with_name.groupby('User-ID').count()['Book-Rating']>=2
x[x].index

Index(['U001', 'U002', 'U003', 'U004', 'U005', 'U006', 'U007', 'U008', 'U009',
       'U010',
       ...
       'U791', 'U792', 'U793', 'U794', 'U795', 'U796', 'U797', 'U798', 'U799',
       'U800'],
      dtype='object', name='User-ID', length=800)

In [24]:
required_users=x[x].index

In [25]:
required_users

Index(['U001', 'U002', 'U003', 'U004', 'U005', 'U006', 'U007', 'U008', 'U009',
       'U010',
       ...
       'U791', 'U792', 'U793', 'U794', 'U795', 'U796', 'U797', 'U798', 'U799',
       'U800'],
      dtype='object', name='User-ID', length=800)

In [26]:
ratings_with_name['User-ID'].isin(required_users)

0       True
1       True
2       True
3       True
4       True
        ...
5008    True
5009    True
5010    True
5011    True
5012    True
Name: User-ID, Length: 5013, dtype: bool

In [27]:
ratings_with_name[ratings_with_name['User-ID'].isin(required_users)]          #store them in ratings with name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Availability
0,U001,9781259002380,0,Electronic Principles,"Albert Paul Malvino, David Bates",2015,McGraw-Hill Education,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://www.amazon.in/dp/1259002380
1,U001,9781259002380,0,Basic Electronics,"Bernard Grob, Mitchel E. Schultz",2014,McGraw-Hill Education,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://www.amazon.in/dp/1259002380
2,U001,9781259002380,0,Switching Theory and Logic Design,A. Anand Kumar,2016,Prentice Hall,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://www.amazon.in/dp/1259002380
3,U001,9781259002380,0,Electrical Machinery,P.S. Bimbhra,2014,Khanna Publishers,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://www.amazon.in/dp/1259002380
4,U002,9788131791862,2,Power Electronics,P.S. Bimbhra,2012,Khanna Publishers,https://covers.openlibrary.org/b/isbn/97881317...,https://covers.openlibrary.org/b/isbn/97881317...,https://covers.openlibrary.org/b/isbn/97881317...,https://www.amazon.in/dp/8131791863
...,...,...,...,...,...,...,...,...,...,...,...
5008,U430,9788187572680,6,Machine Learning: An AI Approach,"Michalski, Carbonell, Mitchell",1983,Springer,https://covers.openlibrary.org/b/isbn/97881875...,https://covers.openlibrary.org/b/isbn/97881875...,https://covers.openlibrary.org/b/isbn/97881875...,https://www.amazon.in/dp/8187572684
5009,U236,978000000110,6,Mechanical Engineering Handbook Vol. 10,Author M10,2015,TechPress,https://example.com/mech_10_S.jpg,https://example.com/mech_10_M.jpg,https://example.com/mech_10_L.jpg,https://example.com/mech_10
5010,U234,9780071770569,4,Build Your Own Electric Vehicle (3rd Edition),Seth Leitman & Bob Brant,2013,McGraw-Hill,https://covers.openlibrary.org/b/isbn/97800717...,https://covers.openlibrary.org/b/isbn/97800717...,https://covers.openlibrary.org/b/isbn/97800717...,https://www.amazon.com/Build-Your-Electric-Veh...
5011,U756,9780140449136,4,The Odyssey,Homer,-800,Penguin Classics,https://covers.openlibrary.org/b/isbn/97801404...,https://covers.openlibrary.org/b/isbn/97801404...,https://covers.openlibrary.org/b/isbn/97801404...,https://www.amazon.in/dp/0140449132
5012,U385,9788121908716,2,Theory of Structures,S. Ramamrutham,2008,Dhanpat Rai Publishing Company,https://covers.openlibrary.org/b/isbn/97881219...,https://covers.openlibrary.org/b/isbn/97881219...,https://covers.openlibrary.org/b/isbn/97881219...,https://www.amazon.in/dp/8121908712

In [28]:
filtered_rating=ratings_with_name[ratings_with_name['User-ID'].isin(required_users)]    #users ke basis pe filtering done

In [29]:
filtered_rating.groupby('Book-Title').count()['Book-Rating']   #tells how many ratings does a book has.

Book-Title
1984                                                     33
Advanced Engineering Mathematics                         25
Advanced Structural Analysis                             35
Aircraft Structures                                      28
An Introduction to Data Structures with Applications     28
                                                         ..
Transport Processes and Separation Process Principles    52
Vehicle Dynamics                                         28
Wastewater Engineering                                   23
Water Supply Engineering                                 22
Zen and the Art of Motorcycle Maintenance                25
Name: Book-Rating, Length: 187, dtype: int64

In [30]:
y=filtered_rating.groupby('Book-Title').count()['Book-Rating']>=5             #convert into bool and store into variable 
famous_books=y[y].index                                                   #create a different df to store all famous books that have no of ratings>=20

In [31]:
famous_books

Index(['1984', 'Advanced Engineering Mathematics',
       'Advanced Structural Analysis', 'Aircraft Structures',
       'An Introduction to Data Structures with Applications',
       'An Introduction to Mechanics',
       'Animal Cell Culture: A Practical Approach',
       'Antennas and Wave Propagation',
       'Automation, Production Systems, and Computer-Integrated Manufacturing',
       'Automobile Engineering',
       ...
       'Theory of Structures', 'Thermodynamics: An Engineering Approach',
       'Thinking, Fast and Slow', 'To Kill a Mockingbird',
       'Tool Engineering and Design',
       'Transport Processes and Separation Process Principles',
       'Vehicle Dynamics', 'Wastewater Engineering',
       'Water Supply Engineering',
       'Zen and the Art of Motorcycle Maintenance'],
      dtype='object', name='Book-Title', length=187)

In [32]:
filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]  #have famous books which are present in main dataset

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Availability
0,U001,9781259002380,0,Electronic Principles,"Albert Paul Malvino, David Bates",2015,McGraw-Hill Education,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://www.amazon.in/dp/1259002380
1,U001,9781259002380,0,Basic Electronics,"Bernard Grob, Mitchel E. Schultz",2014,McGraw-Hill Education,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://www.amazon.in/dp/1259002380
2,U001,9781259002380,0,Switching Theory and Logic Design,A. Anand Kumar,2016,Prentice Hall,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://www.amazon.in/dp/1259002380
3,U001,9781259002380,0,Electrical Machinery,P.S. Bimbhra,2014,Khanna Publishers,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://covers.openlibrary.org/b/isbn/97812590...,https://www.amazon.in/dp/1259002380
4,U002,9788131791862,2,Power Electronics,P.S. Bimbhra,2012,Khanna Publishers,https://covers.openlibrary.org/b/isbn/97881317...,https://covers.openlibrary.org/b/isbn/97881317...,https://covers.openlibrary.org/b/isbn/97881317...,https://www.amazon.in/dp/8131791863
...,...,...,...,...,...,...,...,...,...,...,...
5008,U430,9788187572680,6,Machine Learning: An AI Approach,"Michalski, Carbonell, Mitchell",1983,Springer,https://covers.openlibrary.org/b/isbn/97881875...,https://covers.openlibrary.org/b/isbn/97881875...,https://covers.openlibrary.org/b/isbn/97881875...,https://www.amazon.in/dp/8187572684
5009,U236,978000000110,6,Mechanical Engineering Handbook Vol. 10,Author M10,2015,TechPress,https://example.com/mech_10_S.jpg,https://example.com/mech_10_M.jpg,https://example.com/mech_10_L.jpg,https://example.com/mech_10
5010,U234,9780071770569,4,Build Your Own Electric Vehicle (3rd Edition),Seth Leitman & Bob Brant,2013,McGraw-Hill,https://covers.openlibrary.org/b/isbn/97800717...,https://covers.openlibrary.org/b/isbn/97800717...,https://covers.openlibrary.org/b/isbn/97800717...,https://www.amazon.com/Build-Your-Electric-Veh...
5011,U756,9780140449136,4,The Odyssey,Homer,-800,Penguin Classics,https://covers.openlibrary.org/b/isbn/97801404...,https://covers.openlibrary.org/b/isbn/97801404...,https://covers.openlibrary.org/b/isbn/97801404...,https://www.amazon.in/dp/0140449132
5012,U385,9788121908716,2,Theory of Structures,S. Ramamrutham,2008,Dhanpat Rai Publishing Company,https://covers.openlibrary.org/b/isbn/97881219...,https://covers.openlibrary.org/b/isbn/97881219...,https://covers.openlibrary.org/b/isbn/97881219...,https://www.amazon.in/dp/8121908712

In [33]:
final_ratings=filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]  #have final books that have no of ratings>10

In [34]:
final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

User-ID,U001,U002,U003,U004,U005,U006,U007,U008,U009,U010,...,U791,U792,U793,U794,U795,U796,U797,U798,U799,U800
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Advanced Engineering Mathematics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Advanced Structural Analysis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aircraft Structures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
An Introduction to Data Structures with Applications,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Transport Processes and Separation Process Principles,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vehicle Dynamics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Wastewater Engineering,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Water Supply Engineering,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
pt=final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [36]:
pt.shape

(187, 800)

In [37]:
pt.fillna(0,inplace=True)

In [38]:
pt

User-ID,U001,U002,U003,U004,U005,U006,U007,U008,U009,U010,...,U791,U792,U793,U794,U795,U796,U797,U798,U799,U800
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Advanced Engineering Mathematics,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Advanced Structural Analysis,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Aircraft Structures,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
An Introduction to Data Structures with Applications,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Transport Processes and Separation Process Principles,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Vehicle Dynamics,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Wastewater Engineering,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Water Supply Engineering,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
#we have 800 users and 187 famous books
#now imagine each book as a point in 272 coordinate dimension
#see each book as vector and find similar vecotors by finding euclidin distance formula

## Distance finding

In [40]:
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
cosine_similarity(pt)              #2d numpy array

array([[1.        , 0.        , 0.0040422 , ..., 0.04999409, 0.03998397,
        0.07020385],
       [0.        , 1.        , 0.        , ..., 0.        , 0.02427485,
        0.        ],
       [0.0040422 , 0.        , 1.        , ..., 0.0850577 , 0.        ,
        0.07112587],
       ...,
       [0.04999409, 0.        , 0.0850577 , ..., 1.        , 0.        ,
        0.        ],
       [0.03998397, 0.02427485, 0.        , ..., 0.        , 1.        ,
        0.06700482],
       [0.07020385, 0.        , 0.07112587, ..., 0.        , 0.06700482,
        1.        ]], shape=(187, 187))

In [42]:
cosine_similarity(pt).shape

(187, 187)

In [43]:
similar=cosine_similarity(pt)

In [44]:
similar[0]           #tells the similar distance of book 1 from others

array([1.        , 0.        , 0.0040422 , 0.        , 0.04945343,
       0.        , 0.        , 0.01817843, 0.        , 0.027777  ,
       0.        , 0.0116343 , 0.03958072, 0.04526711, 0.        ,
       0.        , 0.        , 0.        , 0.11085268, 0.06969981,
       0.        , 0.01947655, 0.07940385, 0.        , 0.        ,
       0.0091187 , 0.01881224, 0.        , 0.        , 0.04653335,
       0.05217364, 0.        , 0.        , 0.03114071, 0.        ,
       0.        , 0.        , 0.0029996 , 0.03472361, 0.06459033,
       0.        , 0.00455935, 0.        , 0.03958072, 0.02428721,
       0.02247052, 0.05859533, 0.        , 0.03958072, 0.0081632 ,
       0.        , 0.05154332, 0.        , 0.06776649, 0.        ,
       0.0232414 , 0.03907314, 0.        , 0.        , 0.03939023,
       0.00967011, 0.01280236, 0.01179351, 0.01450466, 0.03673701,
       0.03696446, 0.12215227, 0.06602914, 0.02366255, 0.        ,
       0.04527912, 0.        , 0.06218434, 0.0333981 , 0.02438636,
       0.0594958 , 0.        , 0.01611419, 0.        , 0.02093567,
       0.01490986, 0.        , 0.05806463, 0.00779194, 0.00542636,
       0.04934685, 0.02249673, 0.00489329, 0.02961681, 0.        ,
       0.02608682, 0.06756601, 0.02539104, 0.07229014, 0.06755768,
       0.01951887, 0.03028801, 0.01130389, 0.        , 0.03185218,
       0.        , 0.0228625 , 0.13222219, 0.        , 0.0437436 ,
       0.02289394, 0.04517131, 0.        , 0.        , 0.03092404,
       0.        , 0.00598569, 0.01774947, 0.13198258, 0.02158616,
       0.        , 0.06009138, 0.00540455, 0.        , 0.        ,
       0.02612719, 0.03765817, 0.        , 0.1329853 , 0.00726984,
       0.03673701, 0.22282615, 0.        , 0.00624034, 0.        ,
       0.        , 0.        , 0.02988074, 0.        , 0.        ,
       0.05216663, 0.        , 0.04505216, 0.00824147, 0.07352309,
       0.02111538, 0.05396541, 0.02501227, 0.16695415, 0.        ,
       0.        , 0.04480256, 0.10121148, 0.06985586, 0.        ,
       0.        , 0.0303754 , 0.        , 0.01985331, 0.        ,
       0.        , 0.        , 0.01733219, 0.0040422 , 0.        ,
       0.06513312, 0.02581155, 0.03958072, 0.10123812, 0.00462679,
       0.        , 0.03063947, 0.        , 0.        , 0.01409843,
       0.08579157, 0.        , 0.00260868, 0.02779886, 0.0533705 ,
       0.00720667, 0.        , 0.01439078, 0.        , 0.        ,
       0.02431475, 0.01549788, 0.00440396, 0.00434845, 0.04999409,
       0.03998397, 0.07020385])

In [45]:
def recommend(book_name):           #book name se index fetch krna hai 
    return suggestions

In [46]:
np.where(pt.index=='Antennas and Wave Propagation')[0][0]   #finding index of the book

np.int64(7)

In [47]:
def recommend(book_name): 
    #index fetch
    index=np.where(pt.index=='Antennas and Wave Propagation')[0][0]
    distances=similar[index]        #to find the distances of given book at index with other indexes
    return suggestions

In [48]:
similar[0]                #distance of book at index 0 wwith others

array([1.        , 0.        , 0.0040422 , 0.        , 0.04945343,
       0.        , 0.        , 0.01817843, 0.        , 0.027777  ,
       0.        , 0.0116343 , 0.03958072, 0.04526711, 0.        ,
       0.        , 0.        , 0.        , 0.11085268, 0.06969981,
       0.        , 0.01947655, 0.07940385, 0.        , 0.        ,
       0.0091187 , 0.01881224, 0.        , 0.        , 0.04653335,
       0.05217364, 0.        , 0.        , 0.03114071, 0.        ,
       0.        , 0.        , 0.0029996 , 0.03472361, 0.06459033,
       0.        , 0.00455935, 0.        , 0.03958072, 0.02428721,
       0.02247052, 0.05859533, 0.        , 0.03958072, 0.0081632 ,
       0.        , 0.05154332, 0.        , 0.06776649, 0.        ,
       0.0232414 , 0.03907314, 0.        , 0.        , 0.03939023,
       0.00967011, 0.01280236, 0.01179351, 0.01450466, 0.03673701,
       0.03696446, 0.12215227, 0.06602914, 0.02366255, 0.        ,
       0.04527912, 0.        , 0.06218434, 0.0333981 , 0.02438636,
       0.0594958 , 0.        , 0.01611419, 0.        , 0.02093567,
       0.01490986, 0.        , 0.05806463, 0.00779194, 0.00542636,
       0.04934685, 0.02249673, 0.00489329, 0.02961681, 0.        ,
       0.02608682, 0.06756601, 0.02539104, 0.07229014, 0.06755768,
       0.01951887, 0.03028801, 0.01130389, 0.        , 0.03185218,
       0.        , 0.0228625 , 0.13222219, 0.        , 0.0437436 ,
       0.02289394, 0.04517131, 0.        , 0.        , 0.03092404,
       0.        , 0.00598569, 0.01774947, 0.13198258, 0.02158616,
       0.        , 0.06009138, 0.00540455, 0.        , 0.        ,
       0.02612719, 0.03765817, 0.        , 0.1329853 , 0.00726984,
       0.03673701, 0.22282615, 0.        , 0.00624034, 0.        ,
       0.        , 0.        , 0.02988074, 0.        , 0.        ,
       0.05216663, 0.        , 0.04505216, 0.00824147, 0.07352309,
       0.02111538, 0.05396541, 0.02501227, 0.16695415, 0.        ,
       0.        , 0.04480256, 0.10121148, 0.06985586, 0.        ,
       0.        , 0.0303754 , 0.        , 0.01985331, 0.        ,
       0.        , 0.        , 0.01733219, 0.0040422 , 0.        ,
       0.06513312, 0.02581155, 0.03958072, 0.10123812, 0.00462679,
       0.        , 0.03063947, 0.        , 0.        , 0.01409843,
       0.08579157, 0.        , 0.00260868, 0.02779886, 0.0533705 ,
       0.00720667, 0.        , 0.01439078, 0.        , 0.        ,
       0.02431475, 0.01549788, 0.00440396, 0.00434845, 0.04999409,
       0.03998397, 0.07020385])

In [49]:
##now sort to get the most similar distance/ largest distance

In [50]:
sorted(list(enumerate(similar[0])),key=lambda x:x[1], reverse=True)[1:8]

[(126, np.float64(0.22282615411556617)),
 (143, np.float64(0.166954154360729)),
 (123, np.float64(0.13298530260380803)),
 (102, np.float64(0.13222219370671362)),
 (113, np.float64(0.13198257944919323)),
 (66, np.float64(0.1221522746770799)),
 (18, np.float64(0.11085267978161668))]

In [51]:
def recommend(book_name):
    # Case-insensitive partial match for book titles
    matching_books = final_ratings[final_ratings['Book-Title'].str.contains(book_name, case=False, na=False)]

    if matching_books.empty:
        return f"No books found containing the word: '{book_name}'"

    # Group by Book-Title, Book-Author, and Image, then calculate average rating
    grouped = matching_books.groupby(['Book-Title', 'Book-Author', 'Image-URL-M']).agg({'Book-Rating': 'mean'}).reset_index()

    # Sort by average rating in descending order
    sorted_books = grouped.sort_values(by='Book-Rating', ascending=False)

    # Prepare the final result
    data = []
    for _, row in sorted_books.iterrows():
        item = [row['Book-Title'], row['Book-Author'], row['Image-URL-M'], round(row['Book-Rating'], 2)]
        data.append(item)

    return data

In [64]:
recommend('computer')

[['Computer Architecture',
  'Behrooz Parhami',
  'https://covers.openlibrary.org/b/isbn/9780195154559.0-M.jpg',
  5.77],
 ['Digital Logic and Computer Design',
  'M. Morris Mano',
  'https://covers.openlibrary.org/b/isbn/9780071327695-M.jpg',
  5.76],
 ['The Art of Computer Programming Vol. 1 & 3',
  'Donald Knuth',
  'https://covers.openlibrary.org/b/isbn/9780201896831.0-M.jpg',
  5.33],
 ['Computer Organization and Architecture',
  'William Stallings',
  'https://covers.openlibrary.org/b/isbn/9780134997193.0-M.jpg',
  5.22],
 ['Computer Architecture: A Quantitative Approach',
  'Patterson & Hennessy',
  'https://covers.openlibrary.org/b/isbn/9780128119051.0-M.jpg',
  5.07],
 ['Automation, Production Systems, and Computer-Integrated Manufacturing',
  'Mikell P. Groover',
  'https://covers.openlibrary.org/b/isbn/9780070265127-M.jpg',
  4.72]]

In [53]:
import re

In [54]:
from nltk.stem import PorterStemmer

In [55]:
import nltk

In [56]:
nltk.download('punkt')
stemmer = PorterStemmer()

def stem_text(text):
    """Stem all words in the text."""
    words = re.findall(r'\w+', text.lower())
    return ' '.join(stemmer.stem(w) for w in words)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\XIAOMI\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [57]:
def recommend(book_name):
    # Stem the search term
    search_term_stemmed = stem_text(book_name)

    # Stem book titles for matching
    final_ratings['stemmed_title'] = final_ratings['Book-Title'].apply(stem_text)

    # Filter where stemmed title contains the stemmed search term
    matching_books = final_ratings[
        final_ratings['stemmed_title'].str.contains(search_term_stemmed, na=False)
    ]

    if matching_books.empty:
        return f"No books found containing or similar to: '{book_name}'"

    # Group by original title, author, and image; calculate average rating
    grouped = matching_books.groupby(
        ['Book-Title', 'Book-Author', 'Image-URL-M']
    ).agg({'Book-Rating': 'mean'}).reset_index()

    # Sort by average rating (highest first)
    sorted_books = grouped.sort_values(by='Book-Rating', ascending=False)

    # Prepare result
    data = []
    for _, row in sorted_books.iterrows():
        data.append([
            row['Book-Title'],
            row['Book-Author'],
            row['Image-URL-M'],
            round(row['Book-Rating'], 2)
        ])

    return data

In [58]:
recommend('computer')

[['Computer Architecture',
  'Behrooz Parhami',
  'https://covers.openlibrary.org/b/isbn/9780195154559.0-M.jpg',
  5.77],
 ['Digital Logic and Computer Design',
  'M. Morris Mano',
  'https://covers.openlibrary.org/b/isbn/9780071327695-M.jpg',
  5.76],
 ['The Art of Computer Programming Vol. 1 & 3',
  'Donald Knuth',
  'https://covers.openlibrary.org/b/isbn/9780201896831.0-M.jpg',
  5.33],
 ['Computer Organization and Architecture',
  'William Stallings',
  'https://covers.openlibrary.org/b/isbn/9780134997193.0-M.jpg',
  5.22],
 ['Computer Architecture: A Quantitative Approach',
  'Patterson & Hennessy',
  'https://covers.openlibrary.org/b/isbn/9780128119051.0-M.jpg',
  5.07],
 ['Automation, Production Systems, and Computer-Integrated Manufacturing',
  'Mikell P. Groover',
  'https://covers.openlibrary.org/b/isbn/9780070265127-M.jpg',
  4.72]]

## exporting top 50 books popular-df

In [59]:
import pickle
pickle.dump(merged_df,open('popular.pkl','wb'))   #here the file is made of popular df which will further be exported in vscode

In [60]:
print(merged_df.columns)

Index(['Book-Title', 'Book-Author', 'Image-URL-M', 'num_ratings',
       'avg_ratings', 'Availability'],
      dtype='object')

In [65]:
merged_df

,Book-Title,Book-Author,Image-URL-M,num_ratings,avg_ratings,Availability
0,1984,George Orwell,https://covers.openlibrary.org/b/isbn/97804515...,33,5.545455,https://www.amazon.in/dp/0451524934
1,Advanced Engineering Mathematics,Erwin Kreyszig,https://covers.openlibrary.org/b/isbn/97804704...,25,4.920000,https://www.amazon.com/Advanced-Engineering-Ma...
2,Advanced Structural Analysis,Devdas Menon,https://covers.openlibrary.org/b/isbn/97800706...,35,4.885714,https://www.amazon.in/dp/0070659153
3,Aircraft Structures,David J. Peery,https://covers.openlibrary.org/b/isbn/97881315...,28,5.285714,https://www.amazon.in/dp/8131518155
4,An Introduction to Data Structures with Applic...,Tremblay & Sorenson,https://covers.openlibrary.org/b/isbn/97800746...,28,5.035714,https://www.amazon.in/dp/0074624717
...,...,...,...,...,...,...
193,Transport Processes and Separation Process Pri...,Christie J. Geankoplis,https://covers.openlibrary.org/b/isbn/97812590...,52,5.615385,https://www.amazon.in/dp/1259062763
195,Vehicle Dynamics,Reza N. Jazar,https://covers.openlibrary.org/b/isbn/97881315...,28,6.464286,https://www.amazon.in/dp/8131518783
196,Wastewater Engineering,Metcalf & Eddy,https://covers.openlibrary.org/b/isbn/97881219...,23,5.217391,https://www.amazon.in/dp/8121916666
197,Water Supply Engineering,"B.C. Punmia, Ashok Kumar Jain, Arun Kumar Jain",https://covers.openlibrary.org/b/isbn/97881219...,22,5.545455,https://www.amazon.in/dp/8121916658
198,Zen and the Art of Motorcycle Maintenance,Robert M. Pirsig,https://covers.openlibrary.org/b/isbn/97803854...,25,5.120000,https://www.amazon.in/dp/0385472579

In [67]:
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similar,open('similar.pkl','wb'))

In [68]:
pickle.dump(final_ratings,open('FR.pkl','wb'))